[SBL-219] 데모 AI 설문 초안 생성 API 구현
SUIN-BUNDANG-LINE/Backend pull request #104
Opened 2024-10-26 17:18 UTC by JeongHunHui

## 📢 설명

- 로그인 없이 AI를 활용하여 설문 초안을 생성할 수 있는 **데모 AI 설문 생성 API** 구현
    - endpoint
        - [POST] /api/v1/ai/generate/demo/survey/{visitor-id}
    - pathVariable
        - visitorId, 핑거프린트로 생성된 visitorId
    - requestBody
        
        ```json
        {
          "target": "", // notnull
          "groupName": "", // notnull
          "fileUrl": null, // nullable
          "userPrompt": "아마존 밀림 여행 설문 만들어줘" // notnull
        }
        ```
        
    - responseBody: 기존 AI 설문 생성 API와 동일
- 기존 두 개의 AI 설문 생성 API를 하나로 통합
    - endpoint
        - [POST] /api/v1/ai/generate/survey/{visitor-id}
    - pathVariable
        - surveyId, 설문의 id, UUID
    - requestBody(**데모 AI 설문 생성 API와 동일**)
        
        ```json
        {
          "target": "", // notnull
          "groupName": "", // notnull
          "fileUrl": null, // nullable
          "userPrompt": "아마존 밀림 여행 설문 만들어줘" // notnull
        }
        ```
        
    - responseBody: 기존 AI 설문 생성 API와 동일
- 데모 API 호출 제한을 위해서 Redis 연결 설정 추가
    - 노션 환경설정 페이지 백엔드 부분에서 redis관련 환경변수 업데이트
    - github secrets의 secret yml 업데이트 완료

## ✅ 체크 리스트

- [ ]  application-secret.yml 업데이트(노션 참고, redis 부분만 추가됨)
- [ ]  기존 AI 설문 생성 API가 바뀐 스펙대로 잘 동작하는지 확인
- [ ]  데모 AI 설문 생성 API가 로그인하지 않은 상태에서 잘 동작하는지 확인
    - 프론트와 연계하는 것이 아니면, GenerateService의 FingerprintApi를 FakeFingerprintApi로 수정한 뒤 테스트 진행
- [ ]  데모 AI 설문 생성 API 호출 후 redis에서 `keys *` 명령어로 `demoCount:{visitorId}`와 같은 형태로 키가 생성되었고, `HGETALL {key}` 명령어로 count, expiration(만료일), visitorId가 잘 들어갔는지 확인
    - [ ]  여러번 호출했을 때 count가 잘 오르는지 확인
- [ ]  `TTL {key}` 명령어로 나온 값이 현재 시간 기준 다음날 0시 까지 남은 초와 동일한지 확인 (ex: 23시 정각에 확인 시, 3600이 나와야함)
- [ ]  count가 100보다 커지면 아래와 같은 에러가 발생하는지 확인
    
    ```json
    {
    	"code": "PY0007",
    	"message": "데모 AI 기능은 하루에 100회 까지만 사용 가능합니다.",
    	"errors": []
    }
    ```
    
    100번 호출이 번거롭다면, `AIDemoCountRedisAdapter`의 `MAX_COUNT` 값을 조정

2024-10-27 00:11 UTC, GulSauce commented
redis hash중에서 
-```expiration(만료일)```의 용도가 궁굼합니다
-visitordId는 다음과 같이 저장됩니다  ```key:{visitordId}```. 즉, 키 이름이 "key"인데 의도한 사항인지 궁굼합니다

2024-10-27 00:27 UTC, GulSauce requested changes

2024-10-27 00:27 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
>      @Operation(summary = "파일을 통한 AI 설문 생성")
그냥 AI 설문 생성으로summary를 바꿔야할것같습니다. 감사합니다

2024-10-27 00:29 UTC, GulSauce requested changes

2024-10-27 00:29 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
> +                    chatSessionId = null,
로그인한 사용자는 ```chatSessionId```가 ```surveyId```로써 존재하는데 다 null로 주면 안될것같아요

2024-10-27 06:30 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
> +                    chatSessionId = null,
아 그렇네요.. 수정하겠습니다!

2024-10-27 07:07 UTC, JeongHunHui commented
> 1. redis hash중에서
>    -`expiration(만료일)`의 용도가 궁굼합니다
>    -visitordId는 다음과 같이 저장됩니다  `key:{visitordId}`. 즉, 키 이름이 "key"인데 의도한 사항인지 궁굼합니다

제가 local에만 visitorId로 해두고 push를 안해놨네요 ㅎㅎ.. 만료일 같은 경우도 굳이 저장할 필요가 없을 것 같아서, redis hash 대신 key:string 형식으로 저장하는 식으로 수정하였습니다.

> 2. makerID가 달라도 설문이 생성되어 버리는데 의도한사항인지궁굼합니다

이전 버전 부터 makerId가 달라도 설문이 생성되는 문제가 있었네요... 수정하였습니다!

2024-10-28 01:02 UTC, GulSauce approved these changes
전부 다 잘 됩니다 고생하셨습니다!

2024-10-28 18:23 UTC, merged