[SBL-21] 공통 응답 객체 및 에러 헨들러 구현
SUIN-BUNDANG-LINE/Backend pull request #3
Opened 2024-06-30 16:03 UTC by JeongHunHui

## 📢 설명
- API의 응답 형식을 아래와 같이 정의
    
    ```json
    {
      "code": "응답의 코드, AA0001 과 같은 형식",
      "message": "응답의 메시지",
      "data": {
        // 필요한 데이터
      }
    }
    ```

- 예외 발생 시 응답 형식을 아래와 같이 정의
    
    ```json
    {
      "code": "에러 코드, AA0001 과 같은 형식",
      "message": "에러의 메시지",
      "errors": [
        {
          "field": "요청 필드 명",
          "value": "요청 값",
          "reason": "예외 발생 이유"
        }
      ]
    }
    ```

- 예외 핸들링 관련
    - `GlobalExceptionHandler`에서 발생한 예외들을 핸들링
    - 발생한 예외가 BusinessException 클래스를 상속했다면 해당 예외의 code와 message를 포함하여 응답으로 반환
    - 발생한 예외가 `MethodArgumentNotValidException`(dto validate시 발생하는 예외)면 유효성 검사에 실패한 필드 정보와 이유가 함께 errors 배열에 포함되어 반환

## ✅ 체크 리스트
- [ ] Demo 생성 API(POST, /api/v1/demo) 호출시 응답이 형태대로 잘 오는지 확인
- [ ] Demo 생성 API(POST, /api/v1/demo) 호출시 title을 20자 초과로 설정하거나, 공백으로 설정할 경우 예외가 잘 반환되는지 확인
- [ ] Demo 조회 API(GET, /api/v1/demo/{id}) 호출 시 응답이 형태대로 잘 오는지 확인
- [ ] Demo 조회 API(GET, /api/v1/demo/{id}) 호출 시 없는 id로 조회 시 예외가 잘 반환되는지 확인

2024-06-30 23:48 UTC, GulSauce reviewed
클라이언트가 response를 data.data로 참조하게되어서 부자연스러울수 있다 했는데 key를 data에서 result로 바꿔서 data.result로 참조하게하는것 어떨까요

2024-07-01 01:53 UTC, syndersonlee commented
저 리뷰어 걸어주시면 변경 될 때마다 메일로 확인 가능합니다
우선 코드 자체는 나쁘지 않은 것 같고, 추가로 에러 발생 시 로그 심어주는 로직을 추가하면 좋을 것 같습니다.

2024-07-01 11:41 UTC, JeongHunHui commented
> 클라이언트가 response를 data.data로 참조하게되어서 부자연스러울수 있다 했는데 key를 data에서 result로 바꿔서 data.result로 참조하게하는것 어떨까요

수정했습니다!

2024-07-01 11:47 UTC, JeongHunHui commented
> 저 리뷰어 걸어주시면 변경 될 때마다 메일로 확인 가능합니다 우선 코드 자체는 나쁘지 않은 것 같고, 추가로 에러 발생 시 로그 심어주는 로직을 추가하면 좋을 것 같습니다.

@syndersonlee 감사합니다! 그렇다면 리뷰어 걸어두겠습니다!
![image](https://github.com/SUIN-BUNDANG-LINE/Backend/assets/108508730/350c7574-fd0c-4794-b039-89abed5f962f)
이렇게 에러 핸들러에 `log.error(e.message, e)` 이런식으로 로그 찍게 해두었는데, 혹시 더 추가 필요할까요?

2024-07-01 13:06 UTC, GulSauce requested changes

2024-07-01 13:06 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/demo/dto/request/DemoCreateRequest.kt
> +    @field:Size(max = 10)
- [ ] Demo 생성 API(`POST`, `/api/v1/demo`) 호출시 title을 20자 초과로 설정하거나, 공백으로 설정할 경우 예외가 잘 반환되는지 확인
의 체크리스트와 설정된 길이 제한이 상충됩니다  max = 20으로 수정이 필요해보입니다

2024-07-01 13:09 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/demo/dto/request/DemoCreateRequest.kt
> +    @field:Size(max = 10)
앗 체크리스트를 수정했습니다..!

2024-07-01 13:10 UTC, GulSauce approved these changes

2024-07-01 13:11 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/demo/dto/request/DemoCreateRequest.kt
> +    @field:Size(max = 10)
확인했습닏나

2024-07-02 13:03 UTC, merged