[SBL-139] 설문 제작 AI 서버로의 요청 API 구현
SUIN-BUNDANG-LINE/Backend pull request #66
Opened 2024-09-18 15:41 UTC by GulSauce

## 📢 설명
해당 Pull Request에 대해 간략하게 설명해주세요!

## ✅ 체크 리스트
- [ ] 리뷰어가 체크할 내용을 작성해주세요!

2024-09-20 13:11 UTC, JeongHunHui requested changes
고생 많으셨습니다. 다른 부분은 추후에 진행해도 좋을 것 같고, SurveyGeneratedByAI 관련 리뷰, 에러코드 중복, PythonServerExceptionHandler 관련 리뷰는 확인하고 의견 부탁드립니다.

2024-09-20 13:11 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/ai/domain/SurveyGeneratedByAI.kt
LLM 서버에서 생성되는 설문을 저장하는 객체이므로 domain 객체보다는 dto로 봐야할 것 같습니다. 또한, 지금 SurveyGeneratedByAI 에는 유효성 검증 로직이 없어서 LLM에서 비즈니스 로직에 맞지 않게 설문을 생성하게 되면 이상한 설문이 응답으로 반환될 수 있을 것 같습니다. 그래서 저는 이 dto를 Survey 도메인 객체로 변환시키는 식으로 사용하면 좋을 것 같습니다. (SurveySaveRequest 참고)

그렇게 되면, SurveyGeneratedByAI를 SurveyMakeInfoResponse로 변환하는 로직도 필요없고, 유효성 검증도 챙길 수 있고 코드도 전체적으로 깔끔해질 것 같아요.

2024-09-20 13:11 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/global/util/FileValidator.kt
FileValidator가 원래는 S3Config에서 S3에 업로드하는 파일의 유효성을 검증하도록 Bean을 생성하게 해두었죠.
하지만, GenerateSerice에서 url의 형식(cloud front url 인지 검사)이나 매개변수로 받은 확장자에 해당하는지 검사하는 역할도 수행하게 되었네요. 추후에 단일 역할만 하도록 수정이 필요해보입니다.

2024-09-24 03:09 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/util/FileValidator.kt
그럼 config의 class이름 S3Config를 다른 이름으로 바꾸고 하나의 bean을 더 추가로 등록하겠습니다

2024-09-24 03:53 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/util/FileValidator.kt
리팩터링 했으니 확인 바랍니다

2024-09-24 03:59 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
상세한 설명 감사합니다 말씀해주신대로 변경하였습니다
비동기적 방법도 이해했습니다

2024-09-24 04:02 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
> +    INVALID_FILE_URL(HttpStatus.BAD_REQUEST, "S30001", "유효하지 않은 파일 주소입니다."),
수정완료했습니다

2024-09-24 14:15 UTC, JeongHunHui approved these changes
리뷰드렸던 사항들 다 완벽하게 잘 반영되었네요! 너무 고생 많으셨습니다 👍

2024-09-24 14:31 UTC, merged