Sbl 27 o auth2
SUIN-BUNDANG-LINE/Backend pull request #8
Opened 2024-07-16 19:17 UTC by GulSauce

## 📢 설명
해당 Pull Request에 대해 간략하게 설명해주세요!

## ✅ 체크 리스트
- [ ] Notion 환경설정-Backend 설정들 페이지 참고하여 application-oauth2.yml 생성

- [ ] 카카오 로그인 테스트
- /frontend/login에 접속하여 카카오 로그인 진행
- swagger 페이지에 접속하여 /user/profile API 실행
- 조회된 정보가 빈 값 없이 잘 들어갔는지 확인
- 카카오 로그인은 인증된 휴대전화 번호를 수집하지않으므로 role이 ROLE_USER로 나타나는지 확인
- [ ] 구글 로그인 테스트
- /frontend/login에 접속하여 구글 로그인 진행
- swagger 페이지에 접속하여 /user/profile API 실행
- 조회된 정보가 빈 값없이 잘 들어갔는지 확인
- 구글 로그인은 인증된 휴대전화 번호를 수집하지않으므로 role이 ROLE_USER로 나타나는지 확인
- [ ] 관리자 API 테스트
- 아무 계정으로나 로그인하여 /admin/sessions/logged-in-users API 실행, 403 Forbidden이 응답으로 오는지 확인
- mongodb에 접속하여 users 컬렉션 - 임의 회원의 role을 ROLE_ADMIN으로 변경 
- 그 회원으로 접속하여 /admin/sessions/logged-in-users API 실행, 정상 응답이 오는지 확인
(attribute.name이 users 컬렉션의 _id와 일치하므로 그것으로 식별 가능) 
- /user/logout URL을 입력하여 로그아웃 수행, JSESSIONID 쿠키가 정상적으로 삭제되는지 확인
- 여러 브라우저, 시크릿 모드, 로그아웃 등을 활용하여 여러 계졍으로 접속, 접속된 계정 정보만 모두 응답으로 오는지 확인
- [ ] 그 외 코드 리뷰

==============
제가 직접 리뷰어 네이버 ID를 관리자 ID에 등록해아합니다
- [ ] 네이버 로그인 테스트
- /frontend/login에 접속하여 네이버 로그인 진행
- swagger 페이지에 접속하여 /user/profile API 실행
- 조회된 정보가 빈 값없이 잘 들어갔는지 확인
- 네이버 로그인은 인증된 휴대전화 번호를 수집하므로 role이 ROLE_AUTHENTICATED_USER로 나타나는지 확인

2024-07-17 10:35 UTC, JeongHunHui reviewed
![image](https://github.com/user-attachments/assets/0b04b3d8-9944-4731-a31c-55a036d7c1b4)
소셜로그인 잘 되고, 관리자 기능도 정상 작동합니다!

리뷰 남긴 내용들 한번 확인후 수정 부탁드립니다! 고생 많으셨네요^^

2024-07-17 10:35 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/user/dto/request/UserJoinRequest.kt
> +    fun toDocument() =
DTO와 몽고디비에 사용되는 Document객체가 연관되면 안될 것 같습니다.

2024-07-17 10:35 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
> +            "google" -> GoogleUserInfo(attributes)
Provider를 하드코딩된 문자열로 관리하기 보다는 Enum으로 관리하는 것이 좋아보입니다.

2024-07-17 10:35 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
> +    override fun loadUser(oAuth2UserRequest: OAuth2UserRequest): OAuth2User {
또한, 해당 작업은 쿼리를 두 번 날리기 때문에 추후에 트랜잭션 적용이 필요해보입니다. TODO 주석 달아놓고 추후에 트랜잭션 추가해주면 될 것 같습니다.

2024-07-18 08:51 UTC, GulSauce commented on build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-mustache")
완료했습니다!

2024-07-18 08:51 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
> +    override fun configureViewResolvers(registry: ViewResolverRegistry) {
완료했습니다!

2024-07-18 08:52 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
> +    private val userService: UserService,
완료했습니다!

2024-07-18 08:52 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/dto/request/UserJoinRequest.kt
> +    val providerId: String = "",
서비스 to 어댑터이므로 해당 DTO 삭제했습니다

2024-07-18 08:56 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
> +            else -> throw IllegalArgumentException("지원하지 않는 소셜 로그인입니다.")
완료했습니다

2024-07-18 09:17 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2User.kt
> +    private val attributes: MutableMap<String, Any>,
완료했습니다!

2024-07-18 09:18 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/adapter/UserAdapter.kt
> +    fun join(userJoinRequest: UserJoinRequest) {
완료했습니다!

2024-07-18 09:18 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
> +    override fun loadUser(oAuth2UserRequest: OAuth2UserRequest): OAuth2User {
완료했습니다

2024-07-18 09:21 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
> +    override fun getAllLoggedInUsers(): UserSessionsResponse = adminService.getAllLoggedInUsers(sessionRegistry.allPrincipals)
완료했습니다

2024-07-18 09:21 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
> +    ): UserProfileResponse = userService.getUserProfile(customOAuth2User.name)
완료했습니다

2024-07-18 09:22 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/dto/request/UserJoinRequest.kt
> +    fun toDocument() =
완료했습니다

2024-07-18 09:22 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
> +            "google" -> GoogleUserInfo(attributes)
완료했습니다

2024-07-18 10:32 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/util/RandomNicknameGenerator.kt
완료했습니다 닉네임#${그 닉네임 개수} 형식 사용

2024-07-18 10:32 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/adapter/UserAdapter.kt
> +    fun find(id: String): User =
완료했습니다

2024-07-18 13:56 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
> +                loginPage = "/frontend/login"
완료 했습니다 401을 보냅니다

2024-07-18 13:56 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomLogoutSuccessHandler.kt
> +        redirect(response)
완료했습니다 200을 줍니다

2024-07-18 16:25 UTC, JeongHunHui requested changes
정말 고생 많으셨습니다! 한 번 더 고생 부탁드립니다..

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
우선 loadUser 메서드가 너무 깁니다. 이 메서드 안의 내용들은 User 도메인 클래스에 넣을 수 있는 것은 최대한 넣는 식으로 수정하는 게 나을 것 같습니다. 또한, try-catch문으로 인해 어느 코드에서 에러가 발생할 수 있는지 명시되지 않아 코드 가독성이 많이 낮아집니다. 회의한 대로 find = 못 찾으면 Null 반환 가능, get = 못 찾으면 예외 반환 이렇게 수정해서 nullable한 값을 반환하고, 이를 처리하는 식으로 수정하면 더 읽기 쉬워질 것 같습니다.

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
> +@Controller
RestController("/api/v1/user")
이러한 형태로 수정 부탁드립니다.

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
CustomOAuth2Service 에 남긴 리뷰대로 role 정하는 로직, 닉네임 생성 로직 등 User 도메인과 관련된 로직은 최대한 도메인에서 진행할 수 있도록 수정 부탁드립니다!

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
> +    private fun formatPhoneNumber(phoneNumber: String?): String? =
```
companion object {
    private val validFormattedPhoneNumber = "^010-\\d{4}-\\d{4}$".toRegex()
    private val validUnformattedPhoneNumber = "^010\\d{8}$".toRegex()
}
```
위와 같은 형식으로 정규식을 미리 컴파일 해놓으면 매번 유효성 검증 마다 컴파일하는 비용이 줄어들게 됩니다.

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
> +    @Size(min = 2, max = 10)
아마 이렇게 하면 유효성 검증이 제대로 이루어지지 않을 겁니다. @field:Size(min = 2, max = 10) 이렇게 해야 정상 작동할 것입니다. 하지만 이렇게 하기보다는 저는 init에서 직접 길이 검사를 실행하는 식으로 하는게 좋을 것 같습니다. 이유는 도메인 객체는 최대한 POJO 상태로 유지하여 기술에 영향을 안받게 작성할 수 있고, 해당 유효성 검증이 잘못되었을 때 발생하는 예외로 저희가 정의한 커스텀 Exception을 설정할 수 없기 때문입니다.

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
> +            else -> throw NotAPhoneNumberException()
저는 NotAPhoneNumberException 보다는 유저 생성 시 발생하는 예외는 InvalidUserException으로 통일하고, 세부 예외 사항은 로깅으로 파악하는 식으로 하는게 좋아보입니다. 이유는 User안에서 발생하는 예외마다 클래스를 생성하는 것이 번거롭고, 너무 자세한 예외 사항을 알려주는 것도 좋지 못하기 때문입니다.

2024-07-18 16:25 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
> +    NOT_A_PHONE_NUMBER(HttpStatus.BAD_REQUEST, "US0002", "전화번호 형식이 아입니다."),
표준어로 수정 부탁드립니다.

2024-07-18 17:07 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
> +@Controller
완료했습니다

2024-07-18 17:08 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
이것은 논의한대로 get, find로 구분했습니다

2024-07-18 17:08 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
> +    NOT_A_PHONE_NUMBER(HttpStatus.BAD_REQUEST, "US0002", "전화번호 형식이 아입니다."),
이스터에그입니다

2024-07-18 17:09 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/repository/UserRepositoryImpl.kt
> +    override fun countByNicknameRegex(nicknameRegex: String): Long {
이것은 논의한대로 id를 사용자프로필 조회 시에 보내주는것으로 바꿨습니다

2024-07-18 17:09 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/GoogleUserInfo.kt
> +    override fun getProvider(): String = "google"
수정했습니다

2024-07-18 17:09 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
수정완료했습니다

2024-07-18 18:04 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
> +            else -> throw NotAPhoneNumberException()
수정했습니다

2024-07-18 18:19 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
> +    private fun formatPhoneNumber(phoneNumber: String?): String? =
조언감사합니다 변경했습니다

2024-07-18 18:33 UTC, JeongHunHui approved these changes
고생 많으셨습니다!

2024-07-18 18:42 UTC, merged