Sbl 177 edit chat to python
SUIN-BUNDANG-LINE/Backend pull request #84
Opened 2024-10-06 04:07 UTC by GulSauce

## 📢 설명
해당 Pull Request에 대해 간략하게 설명해주세요!

## ✅ 체크 리스트
- [ ] 리뷰어가 체크할 내용을 작성해주세요!

2024-10-06 08:28 UTC, JeongHunHui requested changes
기능들 전부 잘 동작합니다! 정말 고생 많으셨습니다. 리뷰 남겨둔 몇 가지 사항 수정 제안 드립니다.
리뷰 남긴 사항 외에도 Domain 클래스와 DTO 관련해서 추후에 이야기 해서 개선하면 좋겠습니다.

2024-10-06 08:28 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
> +    fun findSurveyById(id: UUID): Survey? {
이 메서드는 Survey 클래스에서 findSurveyById라고 하는 것이 어색해보입니다. 이 부분은 Service 레이어에서 직접 `survey.id == surveyId` 이런식으로 비교하는 것이 좋아보입니다.

2024-10-06 08:28 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyGenerationResponse.kt
> +        fun of(aiGeneratedSurvey: AIGeneratedSurvey): AISurveyGenerationResponse =
저도 계속 헷갈리고, 기존 코드에도 틀린 부분이 있지만, 정적 팩토리 메서드 네이밍 컨벤션에 의하면 from은 단일 매개변수, of는 다중 매개변수입니다. from으로 수정해주시면 감사하겠습니다.

2024-10-06 09:50 UTC, GulSauce commented on src/main/kotlin/com/sbl/sulmun2yong/ai/repository/ChatRepository.kt
requestEditSurvey(구 레포지토리 메소드)에서 예외까지 처리하는 것이 좋아보입니다
위의 코드는 어댑터에서 에외처리를 하고 있는데 
(어댑터에서 에외처리를 한다면) 도메인으로 변환 + 예외처리 + (다른 처리 가능성 여지 있음) 보다는 
(구 레포지토리 메소드에서 처리를 한다면) 구 레포지토리 메소드에서 통신 + 통신 예외처리 (다른 처리 가능성 여지 없음)로 처리하는 것이 역할 분배가 잘 되어있는 것처럼 보이기 때문입니다

2024-10-07 05:23 UTC, JeongHunHui commented on src/main/kotlin/com/sbl/sulmun2yong/ai/repository/ChatRepository.kt
제가 저때 빠르게 리뷰를 남기느라 코드가 좀 헷갈렸을 수 있는데, 제가 말씀드리고 싶었던건 repository의 메서드를 Adapter로 옮기고, runCatching을 쓰면 좋겠다는 것이었습니다. 그래서 지금 영제님이 수정해주신 코드가 제가 의도했던 방향입니다! 잘 수정해주신 것 같습니다!

2024-10-07 05:26 UTC, JeongHunHui approved these changes
리뷰 남긴 사항들이 깔끔하게 잘 반영된 것 같습니다. 감사합니다 고생하셨습니다~!

2024-10-07 05:43 UTC, merged