[SBL-36] 설문 관련 도메인 클래스 구현 및 테스트 코드 작성
SUIN-BUNDANG-LINE/Backend pull request #9
Opened 2024-07-21 01:35 UTC by JeongHunHui

## 📢 설명
- 설문 관련 도메인 클래스 설계
- 관련 테스트 코드 작성
- 테스트 코드를 통과하도록 구현
- 리팩토링 진행

## 클래스 설명
- 추후 추가

## ✅ 체크 리스트
- [ ] 기존 API 정상 작동 확인
- [ ] survey.domain 패키지의 테스트 커버리지가 100%인지 확인
    ![image](https://github.com/user-attachments/assets/f70e76ba-5e7c-41f6-bc25-253aa2490f1a)
- [ ] 전체적으로 코드가 잘 읽히는지, 구조적으로 문제되는 부분이 있는지 확인
- [ ] 테스트 코드가 올바르게 작성되었는지 확인

2024-07-21 10:08 UTC, GulSauce requested changes

2024-07-21 10:08 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
> +        assertThrows<InvalidSurveyException> { createSurvey(targetParticipants = REWARD_COUNT - 1) }
리워드를             
Reward(UUID.randomUUID(), "아메리카노", "커피", -1),
Reward(UUID.randomUUID(), "카페라떼", "커피", -1),
Reward(UUID.randomUUID(), "햄버거", "음식", -1), 
로 주니까
targetParticipantCount = -3으로 주니 코드가 통과합니다
물론 리워드가 목표참여자수 이하인것맞으나 목표참여자 수를 음수로 설정되게 할 수있는 여지가 보입니다
Reward 도메인을 생성할때도 개수를 validation하는 로직이 필요해보입니다

또한 
```
private fun isTargetParticipantsEnough() = targetParticipants >= getRewardCount()
```
코드를 보았을 때 리워드 개수에 따라 목표 참여자수가 검증되니
함수 이름을 목표 참여자 수는 설문의 리워드 개수 이상이다로 두는게 자연스러워보입니다

2024-07-21 10:33 UTC, JeongHunHui commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
> +    fun `설문의 시작일이 마감일 이후면 예외가 발생한다`() {
우선 이 부분은 비즈니스적으로 정해진게 없어서 아직 넣지 않았는데, 우선 마감일이 현재 날짜로 부터 90일 이후면 예외가 발생하게끔 수정하겠습니다

2024-07-21 10:46 UTC, JeongHunHui commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
> +        assertThrows<InvalidSurveyException> { createSurvey(targetParticipants = REWARD_COUNT - 1) }
이부분은 현재 API 응답 형식과 맞추려고 이렇게 했습니다. 오히려 바꾸면 더 헷갈릴 것 같고 이름이 길어질 것 같기도해서요.

2024-07-21 15:03 UTC, GulSauce requested changes

2024-07-21 15:03 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
count 상한에 대한 테스트 코드 및  예외처리가 필요해보입니다

2024-07-21 15:03 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
getRewardCount()는 리워드를 위한 메소드인데 서베이에서 이를 수행한다면 너무 의존성이 강해지는 것 같습니다 
RewardTest에서 카운트를 가져오는 것을 테스트하지 못하는 것에서도 알 수 있습니다. 이에 대해 의견 부탁드립니다

2024-07-21 16:40 UTC, GulSauce requested changes

2024-07-21 16:45 UTC, JeongHunHui commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
사실 설문의 리워드 개수를 가져온다는 것(`getRewardCount()`)은 여러 종류의 리워드들의 개수의 총 합을 가져오는 것입니다.
즉, **설문에 속한 리워드들의 합계**를 가져오는 것이 목적이기 때문에 리워드 목록을 관리하는 설문의 책임이라고 생각했습니다.

2024-07-21 16:48 UTC, JeongHunHui commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SectionTest.kt
> +    private val tQuestionId = UUID.randomUUID()
우선, 코드의 길이가 너무 길어져서 좀 줄여보고자 이렇게 줄여서 사용하였습니다. 아무래도 테스트 코드다 보니 가독성이 떨어져도, 조금 살펴보면 파악 가능할 것이라고 생각했습니다. 하지만 그래도 변수명을 명확히 짓는 것이 더 좋아보이네요. 수정하겠습니다!

2024-07-21 17:14 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
알겠습니다!

2024-07-21 17:14 UTC, JeongHunHui commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
해당 부분은 TODO 주석 작성 후, 설문 제작 작업 시 구현하겠습니다!

2024-07-21 17:14 UTC, JeongHunHui commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
해당 부분은 TODO 주석 작성 후, 설문 제작 작업 시 구현하겠습니다!

2024-07-21 17:15 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
논의한대로 엣지케이스들 todo로 적어주세요

2024-07-21 17:15 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
> +class RewardTest {
논의한대로 엣지케이스들 todo로 적어주세요

2024-07-21 17:16 UTC, GulSauce commented on src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SectionTest.kt
> +    private val tQuestionId = UUID.randomUUID()
감사합니다

2024-07-23 05:40 UTC, GulSauce requested changes

2024-07-23 05:42 UTC, GulSauce approved these changes
null 관련은 추후에 리팩토링 부탁드립니다

2024-07-23 05:42 UTC, merged